theme: jekyll-theme-cayman
title: DICOMcloud Project
description: Azure friendly DICOMweb part 18 .NET server and client components with qido-rs, wado-rs, stow-rs, wado-uri RESTful implementation http://dicomweb.azurewebsites.net/ 
